[package]
name = "shader_toy_playground"
version = "0.1.1"
authors = ["Knight <790184126@qq.com>"]

[dependencies]
glutin = "*"
gl = "*"
cgmath = "*"
image = "*"
imgui = "*"
glium = "*"
imgui-glium-renderer = "*"