[package]
name = "shader_toy_playground"
version = "0.1.0"
authors = ["Knight <790184126@qq.com>"]

[dependencies]
glutin = "*"
gl = "*"
cgmath = "*"
image = "*"
notify = "*"
imgui = "*"
imgui-glutin-support = "*"
imgui-opengl-renderer = { version = "0.2.4", path = "rust-imgui-opengl-renderer" }